version: '2'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
  server:
    build:
      context: .
    ports:
      - "8080:8080"