spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: update
  security:
    filter:
      order: 10

jwt:
  secret: 'secret'